source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '13.5'

target 'FruitLens' do
  use_frameworks!
  
  pod 'Firebase/Auth'
  pod 'Firebase/Auth'
  pod 'FirebaseAuthInterop'
  pod 'FirebaseCoreDiagnosticsInterop'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'ALLoadingView'
  pod 'GRDB.swift'

end
